apm install sublime-style-column-selection # sublime-style-column-selection
apm install atom-easy-jsdoc # https://atom.io/packages/atom-easy-jsdoc
apm install autocomplete-modules # https://atom.io/packages/autocomplete-modules
apm install autocomplete-paths # https://atom.io/packages/autocomplete-paths
apm install busy-signal # https://atom.io/packages/busy-signal
apm install emmet # https://atom.io/packages/emmet
apm install emmet-jsx-props # https://atom.io/packages/emmet-jsx-props
apm install file-icons # https://atom.io/packages/file-icons
apm install highlight-selected # https://atom.io/packages/highlight-selected
apm install intentions # https://atom.io/packages/intentions
apm install language-babel # https://atom.io/packages/language-babel
apm install language-dotenv # https://atom.io/packages/language-dotenv
apm install language-ejs # https://atom.io/packages/language-ejs
apm install language-gitignore # https://atom.io/packages/language-gitignore
apm install language-graphql # https://atom.io/packages/language-graphql
apm install language-mdx # https://atom.io/packages/language-mdx
apm install linter # https://atom.io/packages/linter
apm install linter-eslint # https://atom.io/packages/linter-eslint
apm install linter-jsonlint # https://atom.io/packages/linter-jsonlint
apm install linter-ui-default # https://atom.io/packages/linter-ui-default
apm install prettier-atom # https://atom.io/packages/prettier-atom
apm install wakatime # https://atom.io/packages/wakatime
